/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/books": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all 15 books, in canonical order */
    get: operations["BooksController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/books/{identifier}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one book */
    get: operations["BooksController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/books/{identifier}/kitabs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the kitabs of a book, in reading order */
    get: operations["BooksController_findKitabs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/books/{identifier}/hadiths": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the hadiths of a book, with per-edition text */
    get: operations["BooksController_findHadiths"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/kitabs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List kitabs, optionally filtered by book */
    get: operations["KitabsController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/kitabs/{identifier}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one kitab */
    get: operations["KitabsController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/kitabs/{identifier}/baabs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the baabs of a kitab, in reading order */
    get: operations["KitabsController_findBaabs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/kitabs/{identifier}/hadiths": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the hadiths of a kitab, with per-edition text */
    get: operations["KitabsController_findHadiths"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/baabs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List baabs, optionally filtered by book or kitab */
    get: operations["BaabsController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/baabs/{identifier}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one baab */
    get: operations["BaabsController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/baabs/{identifier}/hadiths": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the hadiths of a baab, with per-edition text */
    get: operations["BaabsController_findHadiths"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/hadiths": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List hadiths, optionally filtered by book, kitab and/or baab */
    get: operations["HadithsController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/hadiths/{identifier}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one hadith with its texts */
    get: operations["HadithsController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/editions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List editions, filtered by language and/or type */
    get: operations["EditionsController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/editions/{identifier}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one edition */
    get: operations["EditionsController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Service status and database connectivity */
    get: operations["HealthController_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BookDto: {
      /** @description e.g. "HZ1" */
      uci: string;
      /** @description Canonical order; the six sahih come first */
      number: number;
      /** @description UCI prefix of this book's hadiths, e.g. "HB" */
      hadithPrefix: string;
      /** @description e.g. "bukhari" */
      slug: string;
      nameArabic: string;
      nameUrdu: string;
    };
    KitabDto: {
      /** @description e.g. "HK3" */
      uci: string;
      /** @description Global sequence, in reading order */
      number: number;
      bookUci: string;
      /** @description The source database's KitabID */
      sourceId: string;
      numberInBook: number;
      nameArabic: string | null;
      nameUrdu: string | null;
    };
    PaginatedHadiths: {
      data: {
        /** @description e.g. "HB100"; variants end in a letter, "HA270A" */
        uci: string;
        bookPrefix: string;
        kitabUci: string;
        baabUci: string;
        /** @description Hadith number within its own book */
        number: number;
        /** @description 0 for regular hadiths, 1+ for variants */
        subNumber: number;
        grade: string | null;
        takhreej: string | null;
        /** @description One entry per requested edition; may be empty if untranslated */
        texts: {
          /** @description Composite text UCI, e.g. "HX10100100" */
          uci: string;
          editionUci: string;
          /** @description Edition slug, e.g. "ar-vocalized" */
          edition: string;
          text: string;
          footnote: string | null;
        }[];
      }[];
      meta: {
        /** @description 1-based page number that was returned */
        page: number;
        /** @description Maximum items per page */
        limit: number;
        /** @description Total matching rows, ignoring pagination */
        total: number;
        totalPages: number;
      };
    };
    PaginatedKitabs: {
      data: {
        /** @description e.g. "HK3" */
        uci: string;
        /** @description Global sequence, in reading order */
        number: number;
        bookUci: string;
        /** @description The source database's KitabID */
        sourceId: string;
        numberInBook: number;
        nameArabic: string | null;
        nameUrdu: string | null;
      }[];
      meta: {
        /** @description 1-based page number that was returned */
        page: number;
        /** @description Maximum items per page */
        limit: number;
        /** @description Total matching rows, ignoring pagination */
        total: number;
        totalPages: number;
      };
    };
    BaabDto: {
      /** @description e.g. "HY1" */
      uci: string;
      /** @description Global sequence, in reading order */
      number: number;
      kitabUci: string;
      /** @description The source database's BaabHiddenID */
      sourceId: string;
      numberInKitab: number;
      nameArabic: string | null;
      nameUrdu: string | null;
    };
    PaginatedBaabs: {
      data: {
        /** @description e.g. "HY1" */
        uci: string;
        /** @description Global sequence, in reading order */
        number: number;
        kitabUci: string;
        /** @description The source database's BaabHiddenID */
        sourceId: string;
        numberInKitab: number;
        nameArabic: string | null;
        nameUrdu: string | null;
      }[];
      meta: {
        /** @description 1-based page number that was returned */
        page: number;
        /** @description Maximum items per page */
        limit: number;
        /** @description Total matching rows, ignoring pagination */
        total: number;
        totalPages: number;
      };
    };
    HadithDto: {
      /** @description e.g. "HB100"; variants end in a letter, "HA270A" */
      uci: string;
      bookPrefix: string;
      kitabUci: string;
      baabUci: string;
      /** @description Hadith number within its own book */
      number: number;
      /** @description 0 for regular hadiths, 1+ for variants */
      subNumber: number;
      grade: string | null;
      takhreej: string | null;
      /** @description One entry per requested edition; may be empty if untranslated */
      texts: {
        /** @description Composite text UCI, e.g. "HX10100100" */
        uci: string;
        editionUci: string;
        /** @description Edition slug, e.g. "ar-vocalized" */
        edition: string;
        text: string;
        footnote: string | null;
      }[];
    };
    EditionDto: {
      /** @description e.g. "HE1" */
      uci: string;
      number: number;
      /** @description e.g. "ar-vocalized" */
      slug: string;
      name: string;
      /** @description ISO 639-1, e.g. "ar", "ur" */
      language: string;
      /** @enum {string} */
      type: "original" | "translation" | "transliteration";
    };
    HealthDto: {
      /** @enum {string} */
      status: "ok";
      /** @enum {string} */
      db: "up";
      /** @description Process uptime in seconds */
      uptime: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  BooksController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookDto"][];
        };
      };
    };
  };
  BooksController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Number (1), slug (bukhari), UCI (HZ1) or hadith prefix (HB) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookDto"];
        };
      };
    };
  };
  BooksController_findKitabs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Number (1), slug (bukhari), UCI (HZ1) or hadith prefix (HB) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KitabDto"][];
        };
      };
    };
  };
  BooksController_findHadiths: {
    parameters: {
      query?: {
        /** @description 1-based page */
        page?: number;
        /** @description Items per page (max 100) */
        limit?: number;
        /** @description Comma-separated edition slugs, numbers or UCIs, e.g. "ar-vocalized,ur-darussalam". Defaults to "ar-vocalized". */
        edition?: string;
      };
      header?: never;
      path: {
        /** @description Number (1), slug (bukhari), UCI (HZ1) or hadith prefix (HB) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedHadiths"];
        };
      };
    };
  };
  KitabsController_findAll: {
    parameters: {
      query?: {
        /** @description 1-based page */
        page?: number;
        /** @description Items per page (max 100) */
        limit?: number;
        /** @description Book slug, number, UCI or prefix, e.g. "bukhari" */
        book?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedKitabs"];
        };
      };
    };
  };
  KitabsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Global number (3), UCI (HK3) or "<book>:<numberInBook>" (bukhari:3) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KitabDto"];
        };
      };
    };
  };
  KitabsController_findBaabs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Global number (3), UCI (HK3) or "<book>:<numberInBook>" (bukhari:3) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BaabDto"][];
        };
      };
    };
  };
  KitabsController_findHadiths: {
    parameters: {
      query?: {
        /** @description 1-based page */
        page?: number;
        /** @description Items per page (max 100) */
        limit?: number;
        /** @description Comma-separated edition slugs, numbers or UCIs, e.g. "ar-vocalized,ur-darussalam". Defaults to "ar-vocalized". */
        edition?: string;
      };
      header?: never;
      path: {
        /** @description Global number (3), UCI (HK3) or "<book>:<numberInBook>" (bukhari:3) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedHadiths"];
        };
      };
    };
  };
  BaabsController_findAll: {
    parameters: {
      query?: {
        /** @description 1-based page */
        page?: number;
        /** @description Items per page (max 100) */
        limit?: number;
        /** @description Book slug, number, UCI or prefix, e.g. "bukhari" */
        book?: string;
        /** @description Kitab number, UCI or "<book>:<n>", e.g. "HK3" */
        kitab?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedBaabs"];
        };
      };
    };
  };
  BaabsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Global number (1), UCI (HY1) or "<kitab>:<numberInKitab>" (HK3:5, bukhari:3:5) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BaabDto"];
        };
      };
    };
  };
  BaabsController_findHadiths: {
    parameters: {
      query?: {
        /** @description 1-based page */
        page?: number;
        /** @description Items per page (max 100) */
        limit?: number;
        /** @description Comma-separated edition slugs, numbers or UCIs, e.g. "ar-vocalized,ur-darussalam". Defaults to "ar-vocalized". */
        edition?: string;
      };
      header?: never;
      path: {
        /** @description Global number (1), UCI (HY1) or "<kitab>:<numberInKitab>" (HK3:5, bukhari:3:5) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedHadiths"];
        };
      };
    };
  };
  HadithsController_findAll: {
    parameters: {
      query?: {
        /** @description 1-based page */
        page?: number;
        /** @description Items per page (max 100) */
        limit?: number;
        /** @description Comma-separated edition slugs, numbers or UCIs, e.g. "ar-vocalized,ur-darussalam". Defaults to "ar-vocalized". */
        edition?: string;
        /** @description Book slug, number, UCI or prefix, e.g. "bukhari" */
        book?: string;
        /** @description Kitab number, UCI or "<book>:<n>", e.g. "HK3" */
        kitab?: string;
        /** @description Baab number, UCI or "<kitab>:<n>", e.g. "HY1" */
        baab?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedHadiths"];
        };
      };
    };
  };
  HadithsController_findOne: {
    parameters: {
      query?: {
        /** @description Comma-separated edition slugs, numbers or UCIs, e.g. "ar-vocalized,ur-darussalam". Defaults to "ar-vocalized". */
        edition?: string;
      };
      header?: never;
      path: {
        /** @description UCI (HB100) or "<book>:<number>" (bukhari:100). Variant narrations use the dotted source number, e.g. aladab-almufarrad:270.1 (= HA270A). */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HadithDto"];
        };
      };
    };
  };
  EditionsController_findAll: {
    parameters: {
      query?: {
        /** @description Filter by language code, e.g. "ur" */
        language?: string;
        /** @description Filter by edition type */
        type?: "original" | "translation" | "transliteration";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EditionDto"][];
        };
      };
    };
  };
  EditionsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Slug (ur-darussalam), number (2) or UCI (HE2) */
        identifier: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EditionDto"];
        };
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthDto"];
        };
      };
    };
  };
}
